### ISSUE TITLE
Wanted to know if same issue is fixed for playwright as well?

### ISSUE THREAD

**Issue by Rohittater255** [Rohittater255/PlaywrightDownloadIssue#1]
@titusfortner @diemol - I think we can go ahead and close this issue

I have tried using selenium `4.15.0`, coupled with docker tag `4.15.0-20231102`

Just for the sake of completeness, here's the docker compose file

```yaml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.15.0-20231102
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  firefox:
    image: selenium/node-firefox:4.15.0-20231102
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  selenium-hub:
    image: selenium/hub:4.15.0-20231102
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

<details>
<summary>TestNG test running on Chrome</summary>

```java
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.json.Json;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.openqa.selenium.remote.http.Contents.string;

public class SeleniumChromeTest {
    private RemoteWebDriver driver;

    @BeforeTest
    public void setup() throws MalformedURLException {
        String hubUrl = "http://localhost:4444";
        ChromeOptions options = new ChromeOptions();
        options.setEnableDownloads(true);
        driver = new RemoteWebDriver(new URL(hubUrl), options);
        driver.manage().window().maximize();
    }

    @Test
    public void testing() throws InterruptedException, MalformedURLException {
        driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
        driver.findElement(By.id("file-1")).click();
        driver.findElement(By.id("file-2")).click();
        SessionId sessionId = driver.getSessionId();
        System.out.println(sessionId);
        // // Waiting for the file to be remotely downloaded
        TimeUnit.SECONDS.sleep(3);

        HttpRequest request = new HttpRequest(HttpMethod.GET, String.format("/session/%s/se/files", sessionId));
        try (HttpClient client = HttpClient.Factory.createDefault()
                .createClient(new URL("http://localhost:4444/"))) {
            HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            System.out.println(names);
            Assert.assertEquals(names.size(), 2, "Found 2 files downloaded");
        }
    }

    @AfterTest(alwaysRun = true)
    public void quit() {
        driver.quit();
    }
}
```

</details>

<details>
<summary>TestNG test running on Firefox</summary>

```java
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.json.Json;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.openqa.selenium.remote.http.Contents.string;

public class SeleniumFirefoxTest {
    private RemoteWebDriver driver;

    @BeforeTest
    public void setup() throws MalformedURLException {
        String hubUrl = "http://localhost:4444";
        FirefoxOptions options = new FirefoxOptions();
        options.setEnableDownloads(true);
        driver = new RemoteWebDriver(new URL(hubUrl), options);
        driver.manage().window().maximize();
    }

    @Test
    public void testing() throws InterruptedException, MalformedURLException {
        driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
        driver.findElement(By.id("file-1")).click();
        driver.findElement(By.id("file-2")).click();
        SessionId sessionId = driver.getSessionId();
        System.out.println(sessionId);
        // // Waiting for the file to be remotely downloaded
        TimeUnit.SECONDS.sleep(3);

        HttpRequest request = new HttpRequest(HttpMethod.GET, String.format("/session/%s/se/files", sessionId));
        try (HttpClient client = HttpClient.Factory.createDefault()
                .createClient(new URL("http://localhost:4444/"))) {
            HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            System.out.println(names);
            Assert.assertEquals(names.size(), 2, "Found 2 files downloaded");
        }
    }

    @AfterTest(alwaysRun = true)
    public void quit() {
        driver.quit();
    }
}
```

</details>

_Originally posted by @krmahadevan in https://github.com/SeleniumHQ/selenium/issues/12034#issuecomment-1790649468_
